# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestStaffaccept():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_staffaccept(self):
    # Navigate to homepage and login
    self.driver.get("http://localhost/new/")
    self.driver.set_window_size(1327, 736)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("milan@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Milan@07")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    
    # Wait for dashboard to load
    wait = WebDriverWait(self.driver, 10)
    
    # Find and click the Users Management dropdown
    users_management = wait.until(EC.presence_of_element_located((By.XPATH, "//a[contains(text(), 'Users Management')]")))
    users_management.click()
    
    # Wait for dropdown menu to appear and click Staff Requests
    staff_requests = wait.until(EC.presence_of_element_located((By.LINK_TEXT, "Staff Requests")))
    staff_requests.click()
  
