# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestProfile():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    self.wait = WebDriverWait(self.driver, 10)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_profile(self):
    try:
      # Navigate to homepage and login
      self.driver.get("http://localhost/new/")
      self.driver.set_window_size(1337, 752)
      
      # Click login link and wait for login form
      login_link = self.wait.until(EC.presence_of_element_located((By.LINK_TEXT, "Login")))
      login_link.click()
      
      # Wait for and fill login form
      email_field = self.wait.until(EC.presence_of_element_located((By.ID, "email")))
      email_field.click()
      email_field.send_keys("milan2@gmail.com")
      
      password_field = self.driver.find_element(By.ID, "password")
      password_field.send_keys("Milan@07")
      password_field.send_keys(Keys.ENTER)
      
      # Wait for dashboard to load and find profile button
      profile_button = self.wait.until(
        EC.presence_of_element_located((By.XPATH, "//a[contains(., 'My Profile')]"))
      )
      profile_button.click()
      
    except Exception as e:
      # Take a screenshot for debugging
      self.driver.save_screenshot("test_profile_error.png")
      raise Exception(f"Test failed: {str(e)}")
  
